config/routes.rb
Rails.application.routes.draw do

  root 'connects#index'
  resources :connects do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connect.rb
class Connect < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { in: 1..140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/connects_controller.rb
class ConnectsController < ApplicationController
  before_action :set_connect, only: [:show, :edit, :update, :destroy]
  def index
    @connects = Connect.all
  end

  def new
    @connect = Connect.new
  end

  def create
    @connect = Connect.new(connect_params)
    if params[:back]
      render :new
    else
      if @connect.save
        redirect_to connects_path, notice: "ツイートを作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @connect = Connect.find(params[:id])
  end

  def edit
    @connect = Connect.find(params[:id])
  end

  def update
    @connect = Connect.find(params[:id])
    if @connect.update(connect_params)
      redirect_to connects_path, notice: "ツイートを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @connect.destroy
    redirect_to connects_path, notice:"ツイートを削除しました！"
  end

  def confirm
    @connect = Connect.new(connect_params)
    render :new if @connect.invalid?
  end

  private
  def connect_params
    params.require(:connect).permit(:content)
  end

  def set_connect
    @connect = Connect.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connects_helper.rb
module ConnectsHelper
  def choose_new_or_edit
    if action_name == 'new'|| action_name == 'create'
      confirm_connects_path
    elsif action_name == 'edit'
      connect_path
    end
  end
end

app/views/connects/_form.html.erb
<%= form_with(model: @connect, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @connect.errors.any? %>
    <div id="error_explanation">
      <h2><%= @connect.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @connect.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="connect_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "ツイート一覧画面にもどる", connects_path %>

app/views/connects/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @connect, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @connect.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/connects/edit.html.erb
<h2>ツイートを編集する</h2>
<%= render 'form' %>

app/views/connects/index.html.erb
<h1>ツイート一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>内容</th>
  </tr>
<% @connects.each do |connect| %>
  <tr>
    <td><%= connect.content.truncate(24, omission: '...') %></td>
    <td><%= link_to '詳細を確認する', connect_path(connect.id) %></td>
    <td><%= link_to "ツイートを編集する", edit_connect_path(connect.id), data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to 'ツイートを削除する', connect_path(connect.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to '新しくツイートを投稿する', new_connect_path %>

app/views/connects/new.html.erb
<h2>ツイートを作成する</h2>
<%= render 'form' %>

app/views/connects/show.html.erb
<h1>ツイート詳細画面</h1>
<p>内容: <%= @connect.content %></p>
<%= link_to "ツイート一覧画面にもどる", connects_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p>運営会社 Twitter Clone 株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">Twitter  <span class="label label-default">Let's connecting!</span></header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">Twitter</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Twitter</a>
    </div>
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="">top</a></li>
        <li><a href="">menu1</a></li>
        <li><a href="">menu2</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConnectApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= render 'layouts/header' %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>

  </body>
</html>